### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 42Willow** [42Willow/calibre#2]
- [ ] Improve method for installing icons with instructions for Windows
- [ ] Open a GitHub issue with a md table of icons to convert
- [ ] Convert source svgs to a template (maybe?)
- [ ] GitHub action workflow for (converting from template, maybe?) and publishing output icons (pngs) as a release
- [ ] Once the icons are all done, submit them on the mobileread forum
